-- MySQL Script generated by MySQL Workbench
-- Sat 02 Dec 2017 12:56:44 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`table1`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `project`.`table1` (
-- )
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`City` (
  `City_code` INT NOT NULL,
  `City` VARCHAR(45) NULL,
  `Metro` VARCHAR(45) NULL,
  `County` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  PRIMARY KEY (`City_code`),
  UNIQUE INDEX `City_code_UNIQUE` (`City_code` ASC))
ENGINE = InnoDB
COMMENT = 'Contains all information of the city.';


-- -----------------------------------------------------
-- Table `project`.`Price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`Price` (
  `City_code` INT NOT NULL,
  `Nov2010` INT NULL,
  `Dec2010` INT NULL,
  `Jan2011` INT NULL,
  `Feb2011` INT NULL,
  `Mar2011` INT NULL,
  `Apr2011` INT NULL,
  `May2011` INT NULL,
  `Jun2011` INT NULL,
  `Jul2011` INT NULL,
  `Aug2011` INT NULL,
  `Sep2011` INT NULL,
  `Oct2011` INT NULL,
  `Nov2011` INT NULL,
  `Dec2011` INT NULL,
  `Jan2012` INT NULL,
  `Feb2012` INT NULL,
  `Mar2012` INT NULL,
  `Apr2012` INT NULL,
  `May2012` INT NULL,
  `Jun2012` INT NULL,
  `Jul2012` INT NULL,
  `Aug2012` INT NULL,
  `Sept2012` INT NULL,
  `Oct2012` INT NULL,
  `Nov2012` INT NULL,
  `Dec2012` INT NULL,
  `Jan2013` INT NULL,
  `Feb2013` INT NULL,
  `Mar2013` INT NULL,
  `Apr2013` INT NULL,
  `May2013` INT NULL,
  `Jun2013` INT NULL,
  `Jul2013` INT NULL,
  `Aug2013` INT NULL,
  `Sept2013` INT NULL,
  `Oct2013` INT NULL,
  `Nov2013` INT NULL,
  `Dec2013` INT NULL,
  `Jan2014` INT NULL,
  `Feb2014` INT NULL,
  `Mar2014` INT NULL,
  `Apr2014` INT NULL,
  `May2014` INT NULL,
  `Jun2014` INT NULL,
  `Jul2014` INT NULL,
  `Aug2014` INT NULL,
  `Sept2014` INT NULL,
  `Oct2014` INT NULL,
  `Nov2014` INT NULL,
  `Dec2014` INT NULL,
  `Jan2015` INT NULL,
  `Feb2015` INT NULL,
  `Mar2015` INT NULL,
  `Apr2015` INT NULL,
  `May2015` INT NULL,
  `Jun2015` INT NULL,
  `Jul2015` INT NULL,
  `Aug2015` INT NULL,
  `Sept2015` INT NULL,
  `Oct2015` INT NULL,
  `Nov2015` INT NULL,
  `Dec2015` INT NULL,
  `Jan2016` INT NULL,
  `Feb2016` INT NULL,
  `Mar2016` INT NULL,
  `Apr2016` INT NULL,
  `May2016` INT NULL,
  `Jun2016` INT NULL,
  `Jul2016` INT NULL,
  `Aug2016` INT NULL,
  `Sept2016` INT NULL,
  `Oct2016` INT NULL,
  `Nov2016` INT NULL,
  `Dec2016` INT NULL,
  `Jan2017` INT NULL,
  `serialno` INT NOT NULL,
  UNIQUE INDEX `City_code_UNIQUE` (`City_code` ASC),
  PRIMARY KEY (`serialno`),
  UNIQUE INDEX `serialno_UNIQUE` (`serialno` ASC),
  CONSTRAINT `City_code`
    FOREIGN KEY (City_code)
    REFERENCES `project`.`City` (City_code)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Information about price in all cities.';


-- -----------------------------------------------------
-- Table `project`.`PriceSqft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`PriceSqft` (
  `City_code` INT NOT NULL,
  `Nov2010` INT NULL,
  `Dec2010` INT NULL,
  `Jan2011` INT NULL,
  `Feb2011` INT NULL,
  `Mar2011` INT NULL,
  `Apr2011` INT NULL,
  `May2011` INT NULL,
  `Jun2011` INT NULL,
  `Jul2011` INT NULL,
  `Aug2011` INT NULL,
  `Sep2011` INT NULL,
  `Oct2011` INT NULL,
  `Nov2011` INT NULL,
  `Dec2011` INT NULL,
  `Jan2012` INT NULL,
  `Feb2012` INT NULL,
  `Mar2012` INT NULL,
  `Apr2012` INT NULL,
  `May2012` INT NULL,
  `Jun2012` INT NULL,
  `Jul2012` INT NULL,
  `Aug2012` INT NULL,
  `Sept2012` INT NULL,
  `Oct2012` INT NULL,
  `Nov2012` INT NULL,
  `Dec2012` INT NULL,
  `Jan2013` INT NULL,
  `Feb2013` INT NULL,
  `Mar2013` INT NULL,
  `Apr2013` INT NULL,
  `May2013` INT NULL,
  `Jun2013` INT NULL,
  `Jul2013` INT NULL,
  `Aug2013` INT NULL,
  `Sept2013` INT NULL,
  `Oct2013` INT NULL,
  `Nov2013` INT NULL,
  `Dec2013` INT NULL,
  `Jan2014` INT NULL,
  `Feb2014` INT NULL,
  `Mar2014` INT NULL,
  `Apr2014` INT NULL,
  `May2014` INT NULL,
  `Jun2014` INT NULL,
  `Jul2014` INT NULL,
  `Aug2014` INT NULL,
  `Sept2014` INT NULL,
  `Oct2014` INT NULL,
  `Nov2014` INT NULL,
  `Dec2014` INT NULL,
  `Jan2015` INT NULL,
  `Feb2015` INT NULL,
  `Mar2015` INT NULL,
  `Apr2015` INT NULL,
  `May2015` INT NULL,
  `Jun2015` INT NULL,
  `Jul2015` INT NULL,
  `Aug2015` INT NULL,
  `Sept2015` INT NULL,
  `Oct2015` INT NULL,
  `Nov2015` INT NULL,
  `Dec2015` INT NULL,
  `Jan2016` INT NULL,
  `Feb2016` INT NULL,
  `Mar2016` INT NULL,
  `Apr2016` INT NULL,
  `May2016` INT NULL,
  `Jun2016` INT NULL,
  `Jul2016` INT NULL,
  `Aug2016` INT NULL,
  `Sept2016` INT NULL,
  `Oct2016` INT NULL,
  `Nov2016` INT NULL,
  `Dec2016` INT NULL,
  `Jan2017` INT NULL,
  `Population` INT NOT NULL,
  UNIQUE INDEX `City_code_UNIQUE` (`City_code` ASC),
  PRIMARY KEY (`Population`),
  UNIQUE INDEX `Population_UNIQUE` (`Population` ASC),
  CONSTRAINT `City_code1`
    FOREIGN KEY (City_code)
    REFERENCES `project`.`City` (City_code)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Information about price in sq feet in all cities.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
